### ISSUE TITLE
Upgrade gems

### ISSUE THREAD

**Issue by romikoops** [strongqa/howitzer_example_cucumber#13]
<img width="980" alt="screen shot 2018-05-13 at 19 39 12" src="https://user-images.githubusercontent.com/220115/39970061-5d1c608c-56e5-11e8-8767-391bbbf0d204.png">

**Comment by Kapustochka** [comment]
https://github.com/strongqa/howitzer_example_cucumber/pull/15

**Comment by romikoops** [comment]
done in master
